/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Client } from "@dagger.io/dagger"
import { dag as __dagMyDep } from "./my-dep/my-dep.gen.js"
import { dag as __dagPlain } from "./plain/plain.gen.js"
import type {
  ClientMyDepOpts,
  MyDep
} from "./my-dep/my-dep.gen.js"

declare module "@dagger.io/dagger" {
  interface Client {
    /**
     * @deprecated Reach myDep through its own client instead: `import { myDep } from "@dagger.io/my-dep"`.
     */
    myDep(name: string, opts?: ClientMyDepOpts): MyDep
    /**
     * @deprecated Reach plain through its own client instead: `import { plain } from "@dagger.io/plain"`.
     */
    plain(): Promise<string>
  }
}

const __install = (name: string, impl: (...args: any[]) => any): void => {
  Object.defineProperty(Client.prototype, name, {
    configurable: true,
    enumerable: false,
    writable: true,
    value: impl,
  })
}

__install("myDep", (...args: any[]) =>
  (__dagMyDep.myDep as any)(...args),
)

__install("plain", (...args: any[]) =>
  (__dagPlain.plain as any)(...args),
)
