// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen entrypoint --dispatch).

import { Context, connection, getRegisteredClass } from "@dagger.io/dagger"
import { __loadObject as __loadCoreObject } from "./clients/loader.gen.js"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Smoke } from "./src/index"


class __Iface_Greeter {
  constructor(public _ctx: Context) {}

  static fromID(id: string): __Iface_Greeter {
    return new __Iface_Greeter(new Context().selectNode(id, "SmokeGreeter"))
  }

  async id(): Promise<string> {
    return await this._ctx.select("id").execute()
  }

async greet(name: any): Promise<any> {
    const __args: Record<string, any> = {}
    if (name !== undefined) __args["name"] = name
    return await this._ctx.select("greet", __args).execute()
  }
}



function rebuildSmoke(state: any): Smoke {
  const __obj = Object.assign(Object.create(Smoke.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
  }
  return __obj
}

async function serializeSmoke(__obj: Smoke): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  return __state
}



async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Smoke": {
      switch (fnName) {

        case "": {
          const __arg_source = args["source"] === undefined || args["source"] === null ? args["source"] : __loadCoreObject(args["source"], "Directory")
          const __arg_greeting = args["greeting"]
          const __result = await new Smoke(__arg_source, __arg_greeting) as unknown as Smoke
          return await serializeSmoke(__result)
        }

        case "ctr": {
          const __parent = rebuildSmoke(parentJson)
          const __result = await __parent.ctr()
          return await (__result).id()
        }

        case "greet": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_name = args["name"] === undefined || args["name"] === null ? args["name"] : args["name"]
          const __arg_volume = args["volume"] === undefined || args["volume"] === null ? args["volume"] : ({ "Loud": "LOUD", "Quiet": "QUIET" } as Record<string, string>)[args["volume"]] ?? args["volume"]
          const __arg_loud = args["loud"] === undefined || args["loud"] === null ? args["loud"] : args["loud"]
          const __result = await __parent.greet(__arg_name, __arg_volume, __arg_loud)
          return __result
        }

        case "greetAll": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_names = args["names"] === undefined || args["names"] === null ? [] : (args["names"] as any[]).map((__v) => __v)
          const __result = await __parent.greetAll(...__arg_names)
          return __result
        }

        case "nothing": {
          const __parent = rebuildSmoke(parentJson)
          const __result = await __parent.nothing()
          return __result
        }

        case "read": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_path = args["path"] === undefined || args["path"] === null ? args["path"] : args["path"]
          const __result = await __parent.read(__arg_path)
          return __result
        }

        case "withGreeter": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_greeter = args["greeter"] === undefined || args["greeter"] === null ? args["greeter"] : __Iface_Greeter.fromID(args["greeter"])
          const __result = await __parent.withGreeter(__arg_greeter)
          return await (__result).id()
        }
        default:
          throw new Error(`unknown function ${fnName} on Smoke`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

type CallRequest = {
  receiverType: string
  receiverValue: string | null
  fnName: string
  fnArgs: string
}

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = []
  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk))
  }
  return Buffer.concat(chunks).toString("utf8")
}

// receiverValue and fnArgs arrive as JSON *strings*, not as embedded objects: the
// Dang entrypoint builds the request with JSON.encode, which serializes a JSON
// scalar to a string. So each is decoded a second time here.
function decodeRequest(raw: string): {
  receiverType: string
  fnName: string
  parentJson: any
  args: Record<string, any>
} {
  const request = JSON.parse(raw) as CallRequest
  return {
    receiverType: request.receiverType,
    fnName: request.fnName,
    parentJson:
      request.receiverValue === null || request.receiverValue === undefined
        ? null
        : JSON.parse(request.receiverValue),
    args: JSON.parse(request.fnArgs ?? "{}") as Record<string, any>,
  }
}

async function engineCall(): Promise<void> {
  const { receiverType, fnName, parentJson, args } = decodeRequest(await readStdin())

  await connection(
    async () => {
      // No serve here: a module is only ever reached through a `dag.<module>()`
      // call, and each generated client serves its own module before its first
      // query.
      const result = await invoke(receiverType, fnName, parentJson, args)
      process.stdout.write(
        result === undefined || result === null ? "null" : JSON.stringify(result),
      )
    },
    // stdout is the result channel now, so the session's logs go to stderr. The
    // engine reads one and streams the other; crossing them corrupts the result.
    { LogOutput: process.stderr },
  )
}

// The mode is checked rather than ignored so that a stale entrypoint — one
// generated against a different protocol — fails here with something readable
// instead of hanging on a stdin that never arrives.
async function main(): Promise<void> {
  const mode = process.argv[2]
  if (mode !== "engine-call") {
    throw new Error(`unknown mode ${JSON.stringify(mode ?? "")}; want "engine-call"`)
  }
  return engineCall()
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})