// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen entrypoint --dispatch).

import { Context, connection, getRegisteredClass } from "@dagger.io/dagger"
import * as __dagger from "@dagger.io/dagger"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Smoke } from "./src/index"

// Load a core/dependency object from its ID via node(id:) and wrap it in the
// matching generated client class. Mirrors the SDK runtime loader; replaces the
// retired load<Type>FromID API (removed in #12041). Some core type names
// collide with JS builtins and get a trailing "_" (e.g. "Module" -> Module_).
function __loadCoreObject(id: string, typeName: string): any {
  const cls =
    (__dagger as any)[typeName] ?? (__dagger as any)[typeName + "_"]
  if (!cls) {
    throw new Error(`generated client class not found for core type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}


class __Iface_Greeter {
  constructor(public _ctx: Context) {}

  static fromID(id: string): __Iface_Greeter {
    return new __Iface_Greeter(new Context().selectNode(id, "SmokeGreeter"))
  }

  async id(): Promise<string> {
    return await this._ctx.select("id").execute()
  }

async greet(name: any): Promise<any> {
    const __args: Record<string, any> = {}
    if (name !== undefined) __args["name"] = name
    return await this._ctx.select("greet", __args).execute()
  }
}



function rebuildSmoke(state: any): Smoke {
  const __obj = Object.assign(Object.create(Smoke.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
  }
  return __obj
}

async function serializeSmoke(__obj: Smoke): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  return __state
}



async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Smoke": {
      switch (fnName) {

        case "": {
          const __arg_source = args["source"] === undefined || args["source"] === null ? args["source"] : __loadCoreObject(args["source"], "Directory")
          const __arg_greeting = args["greeting"]
          const __result = await new Smoke(__arg_source, __arg_greeting) as unknown as Smoke
          return await serializeSmoke(__result)
        }

        case "ctr": {
          const __parent = rebuildSmoke(parentJson)
          const __result = await __parent.ctr()
          return await (__result).id()
        }

        case "greet": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_name = args["name"] === undefined || args["name"] === null ? args["name"] : args["name"]
          const __arg_volume = args["volume"] === undefined || args["volume"] === null ? args["volume"] : ({ "Loud": "LOUD", "Quiet": "QUIET" } as Record<string, string>)[args["volume"]] ?? args["volume"]
          const __arg_loud = args["loud"] === undefined || args["loud"] === null ? args["loud"] : args["loud"]
          const __result = await __parent.greet(__arg_name, __arg_volume, __arg_loud)
          return __result
        }

        case "greetAll": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_names = args["names"] === undefined || args["names"] === null ? [] : (args["names"] as any[]).map((__v) => __v)
          const __result = await __parent.greetAll(...__arg_names)
          return __result
        }

        case "nothing": {
          const __parent = rebuildSmoke(parentJson)
          const __result = await __parent.nothing()
          return __result
        }

        case "read": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_path = args["path"] === undefined || args["path"] === null ? args["path"] : args["path"]
          const __result = await __parent.read(__arg_path)
          return __result
        }

        case "withGreeter": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_greeter = args["greeter"] === undefined || args["greeter"] === null ? args["greeter"] : __Iface_Greeter.fromID(args["greeter"])
          const __result = await __parent.withGreeter(__arg_greeter)
          return await (__result).id()
        }
        default:
          throw new Error(`unknown function ${fnName} on Smoke`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

type CallRequest = {
  receiverType: string
  receiverValue: string | null
  fnName: string
  fnArgs: string
}

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = []
  for await (const chunk of process.stdin) {
    chunks.push(Buffer.from(chunk))
  }
  return Buffer.concat(chunks).toString("utf8")
}

// receiverValue and fnArgs arrive as JSON *strings*, not as embedded objects: the
// Dang entrypoint builds the request with JSON.encode, which serializes a JSON
// scalar to a string. So each is decoded a second time here.
function decodeRequest(raw: string): {
  receiverType: string
  fnName: string
  parentJson: any
  args: Record<string, any>
} {
  const request = JSON.parse(raw) as CallRequest
  return {
    receiverType: request.receiverType,
    fnName: request.fnName,
    parentJson:
      request.receiverValue === null || request.receiverValue === undefined
        ? null
        : JSON.parse(request.receiverValue),
    args: JSON.parse(request.fnArgs ?? "{}") as Record<string, any>,
  }
}

async function engineCall(): Promise<void> {
  const { receiverType, fnName, parentJson, args } = decodeRequest(await readStdin())

  await connection(
    async () => {
      const result = await invoke(receiverType, fnName, parentJson, args)
      process.stdout.write(
        result === undefined || result === null ? "null" : JSON.stringify(result),
      )
    },
    // stdout is the result channel now, so the session's logs go to stderr. The
    // engine reads one and streams the other; crossing them corrupts the result.
    { LogOutput: process.stderr },
  )
}

// Developer mode: run a function without the engine loading the module at all.
//
//   npx tsx __dagger.dispatch.ts call <FUNCTION> [--arg value ...]
//
// The receiver is built by running its constructor with no arguments, so a
// module whose constructor has required arguments is engine-only for now.
async function developerCall(argv: string[]): Promise<void> {
  const fnName = argv[0]
  if (fnName === undefined) {
    throw new Error("usage: call <FUNCTION> [--arg value ...]")
  }

  const args: Record<string, any> = {}
  for (let i = 1; i < argv.length; i++) {
    const flag = argv[i]
    if (!flag.startsWith("--")) {
      throw new Error(`expected a --flag, got ${JSON.stringify(flag)}`)
    }
    const name = flag.slice(2)
    const next = argv[i + 1]
    // A flag with no value, or followed by another flag, is a boolean.
    if (next === undefined || next.startsWith("--")) {
      args[name] = true
      continue
    }
    try {
      args[name] = JSON.parse(next)
    } catch {
      args[name] = next
    }
    i++
  }

  await connection(
    async () => {
      const parent = await invoke("Smoke", "", null, {})
      const result = await invoke("Smoke", fnName, parent, args)
      const out =
        result === undefined || result === null
          ? "null"
          : typeof result === "string"
            ? result
            : JSON.stringify(result)
      process.stdout.write(out + "\n")
    },
    { LogOutput: process.stderr },
  )
}

async function main(): Promise<void> {
  const [mode, ...rest] = process.argv.slice(2)
  switch (mode) {
    case "engine-call":
      return engineCall()
    case "call":
      return developerCall(rest)
    default:
      throw new Error(`unknown mode ${JSON.stringify(mode ?? "")}; want "engine-call" or "call"`)
  }
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})