// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import * as __dagger from "@dagger.io/dagger"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Smoke } from "./src/index"

// Load a core/dependency object from its ID via node(id:) and wrap it in the
// matching generated client class. Mirrors the SDK runtime loader; replaces the
// retired load<Type>FromID API (removed in #12041). Some core type names
// collide with JS builtins and get a trailing "_" (e.g. "Module" -> Module_).
function __loadCoreObject(id: string, typeName: string): any {
  const cls =
    (__dagger as any)[typeName] ?? (__dagger as any)[typeName + "_"]
  if (!cls) {
    throw new Error(`generated client class not found for core type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}


class __Iface_Greeter {
  constructor(public _ctx: Context) {}

  static fromID(id: string): __Iface_Greeter {
    return new __Iface_Greeter(new Context().selectNode(id, "SmokeGreeter"))
  }

  async id(): Promise<string> {
    return await this._ctx.select("id").execute()
  }

async greet(name: any): Promise<any> {
    const __args: Record<string, any> = {}
    if (name !== undefined) __args["name"] = name
    return await this._ctx.select("greet", __args).execute()
  }
}



function rebuildSmoke(state: any): Smoke {
  const __obj = Object.assign(Object.create(Smoke.prototype), state ?? {})
  if (state) {
    if (state["source"] !== undefined && state["source"] !== null) {
      __obj["source"] = __loadCoreObject(state["source"], "Directory")
    }
  }
  return __obj
}

async function serializeSmoke(__obj: Smoke): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  if ((__obj as any)["source"] !== undefined && (__obj as any)["source"] !== null) {
    __state["source"] = await ((__obj as any)["source"]).id()
  }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  let obj_Smoke = dag.typeDef().withObject("Smoke", { description: "A module covering the shapes the entrypoint has to dispatch.", sourceMap: dag.sourceMap("src/index.ts", 27, 14) })
  obj_Smoke = obj_Smoke.withFunction(dag.function_("ctr", dag.typeDef().withObject("Container")).withSourceMap(dag.sourceMap("src/index.ts", 64, 3)))
  obj_Smoke = obj_Smoke.withFunction(dag.function_("greet", dag.typeDef().withKind(TypeDefKind.StringKind)).withDescription("Greet someone.").withSourceMap(dag.sourceMap("src/index.ts", 46, 3)).withArg("name", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 46, 9) }).withArg("volume", dag.typeDef().withEnum("Volume"), { sourceMap: dag.sourceMap("src/index.ts", 46, 23) }).withArg("loud", dag.typeDef().withKind(TypeDefKind.BooleanKind).withOptional(true), { sourceMap: dag.sourceMap("src/index.ts", 46, 39) }))
  obj_Smoke = obj_Smoke.withFunction(dag.function_("greetAll", dag.typeDef().withKind(TypeDefKind.StringKind)).withDescription("Greet everyone.").withSourceMap(dag.sourceMap("src/index.ts", 54, 3)).withArg("names", dag.typeDef().withListOf(dag.typeDef().withKind(TypeDefKind.StringKind)).withOptional(true), { sourceMap: dag.sourceMap("src/index.ts", 54, 15) }))
  obj_Smoke = obj_Smoke.withFunction(dag.function_("nothing", dag.typeDef().withKind(TypeDefKind.VoidKind).withOptional(true)).withSourceMap(dag.sourceMap("src/index.ts", 74, 3)))
  obj_Smoke = obj_Smoke.withFunction(dag.function_("read", dag.typeDef().withKind(TypeDefKind.StringKind)).withSourceMap(dag.sourceMap("src/index.ts", 69, 9)).withArg("path", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 69, 14) }))
  obj_Smoke = obj_Smoke.withFunction(dag.function_("withGreeter", dag.typeDef().withInterface("Greeter")).withSourceMap(dag.sourceMap("src/index.ts", 59, 3)).withArg("greeter", dag.typeDef().withInterface("Greeter"), { sourceMap: dag.sourceMap("src/index.ts", 59, 15) }))
  obj_Smoke = obj_Smoke.withField("greeting", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 35, 3) })
  obj_Smoke = obj_Smoke.withField("source", dag.typeDef().withObject("Directory"), { description: "Where the source lives.", sourceMap: dag.sourceMap("src/index.ts", 32, 3) })
  obj_Smoke = obj_Smoke.withConstructor(dag.function_("", obj_Smoke).withArg("source", dag.typeDef().withObject("Directory"), { sourceMap: dag.sourceMap("src/index.ts", 37, 15) }).withArg("greeting", dag.typeDef().withKind(TypeDefKind.StringKind), { defaultValue: JSON.stringify("hello") as string & { __JSON: never }, sourceMap: dag.sourceMap("src/index.ts", 37, 34) }))
  mod = mod.withObject(obj_Smoke)
  let enum_Volume = dag.typeDef().withEnum("Volume", { description: "How loudly to greet.", sourceMap: dag.sourceMap("src/index.ts", 7, 14) })
  enum_Volume = enum_Volume.withEnumMember("Loud", { description: "Shout it.", sourceMap: dag.sourceMap("src/index.ts", 13, 19), value: "LOUD" })
  enum_Volume = enum_Volume.withEnumMember("Quiet", { sourceMap: dag.sourceMap("src/index.ts", 8, 19), value: "QUIET" })
  mod = mod.withEnum(enum_Volume)
  let iface_Greeter = dag.typeDef().withInterface("Greeter", { description: "Anything that can greet.", sourceMap: dag.sourceMap("src/index.ts", 19, 18) })
  iface_Greeter = iface_Greeter.withFunction(dag.function_("greet", dag.typeDef().withKind(TypeDefKind.StringKind)).withSourceMap(dag.sourceMap("src/index.ts", 20, 3)).withArg("name", dag.typeDef().withKind(TypeDefKind.StringKind), { sourceMap: dag.sourceMap("src/index.ts", 20, 11) }))
  mod = mod.withInterface(iface_Greeter)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Smoke": {
      switch (fnName) {

        case "": {
          const __arg_source = args["source"] === undefined || args["source"] === null ? args["source"] : __loadCoreObject(args["source"], "Directory")
          const __arg_greeting = args["greeting"]
          const __result = await new Smoke(__arg_source, __arg_greeting) as unknown as Smoke
          return await serializeSmoke(__result)
        }

        case "ctr": {
          const __parent = rebuildSmoke(parentJson)
          const __result = await __parent.ctr()
          return await (__result).id()
        }

        case "greet": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_name = args["name"] === undefined || args["name"] === null ? args["name"] : args["name"]
          const __arg_volume = args["volume"] === undefined || args["volume"] === null ? args["volume"] : ({ "Loud": "LOUD", "Quiet": "QUIET" } as Record<string, string>)[args["volume"]] ?? args["volume"]
          const __arg_loud = args["loud"] === undefined || args["loud"] === null ? args["loud"] : args["loud"]
          const __result = await __parent.greet(__arg_name, __arg_volume, __arg_loud)
          return __result
        }

        case "greetAll": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_names = args["names"] === undefined || args["names"] === null ? [] : (args["names"] as any[]).map((__v) => __v)
          const __result = await __parent.greetAll(...__arg_names)
          return __result
        }

        case "nothing": {
          const __parent = rebuildSmoke(parentJson)
          const __result = await __parent.nothing()
          return __result
        }

        case "read": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_path = args["path"] === undefined || args["path"] === null ? args["path"] : args["path"]
          const __result = await __parent.read(__arg_path)
          return __result
        }

        case "withGreeter": {
          const __parent = rebuildSmoke(parentJson)
          const __arg_greeter = args["greeter"] === undefined || args["greeter"] === null ? args["greeter"] : __Iface_Greeter.fromID(args["greeter"])
          const __result = await __parent.withGreeter(__arg_greeter)
          return await (__result).id()
        }
        default:
          throw new Error(`unknown function ${fnName} on Smoke`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})