// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen generate-entrypoint).

import { Context, Error as DaggerError, FunctionCachePolicy, TypeDefKind, connection, dag, getRegisteredClass } from "@dagger.io/dagger"
import * as __dagger from "@dagger.io/dagger"
import * as telemetry from "@dagger.io/dagger/telemetry"
import { Ifaces, Widget } from "./src/index"

// Load a core/dependency object from its ID via node(id:) and wrap it in the
// matching generated client class. Mirrors the SDK runtime loader; replaces the
// retired load<Type>FromID API (removed in #12041). Some core type names
// collide with JS builtins and get a trailing "_" (e.g. "Module" -> Module_).
function __loadCoreObject(id: string, typeName: string): any {
  const cls =
    (__dagger as any)[typeName] ?? (__dagger as any)[typeName + "_"]
  if (!cls) {
    throw new Error(`generated client class not found for core type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}

function formatError(e: unknown): DaggerError {
  if (e instanceof Error) {
    let error = dag.error(e.message)
    const ext = (e as { extensions?: Record<string, unknown> }).extensions
    if (ext) {
      for (const [k, v] of Object.entries(ext)) {
        if (v !== "" && v !== undefined && v !== null) {
          error = error.withValue(
            k,
            JSON.stringify(v) as string & { __JSON: never },
          )
        }
      }
    }
    return error
  }
  try {
    return dag.error(JSON.stringify(e))
  } catch {
    return dag.error(String(e))
  }
}


class __Iface_Greeter {
  constructor(public _ctx: Context) {}

  static fromID(id: string): __Iface_Greeter {
    return new __Iface_Greeter(new Context().selectNode(id, "IfacesGreeter"))
  }

  async id(): Promise<string> {
    return await this._ctx.select("id").execute()
  }

async chain(): Promise<any> {
    const __args: Record<string, any> = {}
    return new __Iface_Greeter(this._ctx.select("chain", __args))
  }

async ctr(): Promise<any> {
    const __args: Record<string, any> = {}
    const __id = await this._ctx.select("ctr", __args).select("id").execute<string>()
    return __loadCoreObject(__id, "Container")
  }

async ctrs(): Promise<any> {
    const __args: Record<string, any> = {}
    const __ids = await this._ctx.select("ctrs", __args).select("id").execute<{id: string}[]>()
    return __ids.map(({ id }) => __loadCoreObject(id, "Container"))
  }

async speaker(): Promise<any> {
    const __args: Record<string, any> = {}
    return new __Iface_Speaker(this._ctx.select("speaker", __args))
  }

async widget(): Promise<any> {
    const __args: Record<string, any> = {}
    const __id = await this._ctx.select("widget", __args).select("id").execute<string>()
    return rebuildWidget({ id: __id })
  }
}


class __Iface_Speaker {
  constructor(public _ctx: Context) {}

  static fromID(id: string): __Iface_Speaker {
    return new __Iface_Speaker(new Context().selectNode(id, "IfacesSpeaker"))
  }

  async id(): Promise<string> {
    return await this._ctx.select("id").execute()
  }

async say(): Promise<any> {
    const __args: Record<string, any> = {}
    return await this._ctx.select("say", __args).execute()
  }
}



function rebuildIfaces(state: any): Ifaces {
  const __obj = Object.assign(Object.create(Ifaces.prototype), state ?? {})
  if (state) {
  }
  return __obj
}

async function serializeIfaces(__obj: Ifaces): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  return __state
}

function rebuildWidget(state: any): Widget {
  const __obj = Object.assign(Object.create(Widget.prototype), state ?? {})
  if (state) {
  }
  return __obj
}

async function serializeWidget(__obj: Widget): Promise<any> {
  if (__obj === null || __obj === undefined) return __obj
  const __state: any = { ...__obj }
  return __state
}



async function register(): Promise<string> {
  let mod = dag.module_()
  let obj_Ifaces = dag.typeDef().withObject("Ifaces", { description: "Module entrypoint." })
  obj_Ifaces = obj_Ifaces.withFunction(dag.function_("greeter", dag.typeDef().withInterface("Greeter")).withArg("greeter", dag.typeDef().withInterface("Greeter")))
  mod = mod.withObject(obj_Ifaces)
  let obj_Widget = dag.typeDef().withObject("Widget", { description: "A module-owned object an interface method returns." })
  obj_Widget = obj_Widget.withField("label", dag.typeDef().withKind(TypeDefKind.StringKind))
  mod = mod.withObject(obj_Widget)
  let iface_Greeter = dag.typeDef().withInterface("Greeter", { description: "Returns every object-ish shape an interface method can return." })
  iface_Greeter = iface_Greeter.withFunction(dag.function_("chain", dag.typeDef().withInterface("Greeter")).withDescription("The same interface — the only case the old renderer got right."))
  iface_Greeter = iface_Greeter.withFunction(dag.function_("ctr", dag.typeDef().withObject("Container")).withDescription("A core object."))
  iface_Greeter = iface_Greeter.withFunction(dag.function_("ctrs", dag.typeDef().withListOf(dag.typeDef().withObject("Container"))).withDescription("A list of core objects, the branch that was already correct."))
  iface_Greeter = iface_Greeter.withFunction(dag.function_("speaker", dag.typeDef().withInterface("Speaker")).withDescription("A different interface declared by this module."))
  iface_Greeter = iface_Greeter.withFunction(dag.function_("widget", dag.typeDef().withObject("Widget")).withDescription("An object declared by this module."))
  mod = mod.withInterface(iface_Greeter)
  let iface_Speaker = dag.typeDef().withInterface("Speaker", { description: "A second interface, so Greeter can return something that is not itself." })
  iface_Speaker = iface_Speaker.withFunction(dag.function_("say", dag.typeDef().withKind(TypeDefKind.StringKind)))
  mod = mod.withInterface(iface_Speaker)
  return await mod.id()
}

async function invoke(
  parentName: string,
  fnName: string,
  parentJson: any,
  args: Record<string, any>,
): Promise<any> {
  switch (parentName) {
    case "Ifaces": {
      switch (fnName) {

        case "": {
          const __result = new Ifaces()
          return await serializeIfaces(__result)
        }

        case "greeter": {
          const __parent = rebuildIfaces(parentJson)
          const __arg_greeter = args["greeter"] === undefined || args["greeter"] === null ? args["greeter"] : __Iface_Greeter.fromID(args["greeter"])
          const __result = await __parent.greeter(__arg_greeter)
          return await (__result).id()
        }
        default:
          throw new Error(`unknown function ${fnName} on Ifaces`)
      }
    }
    case "Widget": {
      switch (fnName) {

        case "": {
          const __result = new Widget()
          return await serializeWidget(__result)
        }
        default:
          throw new Error(`unknown function ${fnName} on Widget`)
      }
    }
    default:
      throw new Error(`unknown object ${parentName}`)
  }
}

async function dispatch() {
  await connection(async () => {
    const fnCall = dag.currentFunctionCall()
    const parentName = await fnCall.parentName()

    if (parentName === "") {
      const id = await register()
      await fnCall.returnValue(JSON.stringify(id) as string & { __JSON: never })
      return
    }

    const fnName = await fnCall.name()
    const parentJson = JSON.parse(await fnCall.parent())
    const fnArgs = await fnCall.inputArgs()

    const args: Record<string, any> = {}
    for (const arg of fnArgs) {
      args[await arg.name()] = JSON.parse(await arg.value())
    }

    try {
      const result = await invoke(parentName, fnName, parentJson, args)
      const out = result === undefined || result === null ? "null" : JSON.stringify(result)
      await fnCall.returnValue(out as string & { __JSON: never })
    } catch (e: unknown) {
      await fnCall.returnError(formatError(e))
      process.exit(1)
    }
  }, { LogOutput: process.stdout })
}

dispatch().catch((e) => {
  console.error(e)
  process.exit(2)
})