{{- /* Per-module generated client file.

Renders one module — a dependency, a client target, or the module itself — as a
self-contained client: the module's own types, plus a root `Client` class built
from the fields the module contributes to Query, a `dag` instance bound to the
shared session, and one top-level function per root field mirroring it, so
consumers write `hey.hey()` / `hey.loadHeyFromID(id)` instead of reaching those
fields through the core client.

The data shape matches the "api" template ({Schema, SchemaVersion, Types,
DepName}); Types has been pre-filtered (via Schema.Include) to the types
contributed by this module — for the extendable types, Include keeps the type
but strips its fields down to the module-contributed ones, and those fields are
what becomes this file's own Client. Nothing here merges into the core Client:
the core file neither imports nor re-exports this one, so the two clients only
meet through the session they share. */ -}}
{{ define "module_client" -}}
/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context, BaseClient } from "{{ ClientRuntimeImport }}"
{{- if .Bound }}
{{- /* The core dag runs this module's serve — it carries no serve of its own,
so serving through it cannot recurse. */}}
import { dag as __dag } from "@dagger.io/dagger"
{{- end }}

{{- /* Types owned by the core library or by a sibling module are imported from
their owning file. Object classes are value imports — the bodies construct them
(`new Container(ctx)`) and call enum converters — everything else appears only
in signatures and stays type-only. The import direction is strictly
client -> library, so no ESM cycle; a sibling value import is only ever
dereferenced inside a method body, after both modules have evaluated. */}}
{{- range $imp := ClientImports .Types .DepName }}
{{- if $imp.Values }}
import {
{{- range $i, $n := $imp.Values }}{{ if $i }},{{ end }}
  {{ $n }}
{{- end }}
} from "{{ $imp.From }}"
{{- end }}
{{- if $imp.Types }}
import type {
{{- range $i, $n := $imp.Types }}{{ if $i }},{{ end }}
  {{ $n }}
{{- end }}
} from "{{ $imp.From }}"
{{- end }}
{{- end }}

{{ template "types" . }}

{{- /* The module's own object classes. The extendable types are skipped here:
the module's contributed root fields become this file's Client below. */ -}}
{{- range .Types }}
	{{- if HasPrefix .Name "_" }}
		{{- /* internal type, skip */ -}}
	{{- else if IsExtendableType . }}
		{{- /* rendered as this file's Client below */ -}}
	{{- else if IsInterface . }}
{{""}}	{{- template "interface" . }}
	{{- else }}
{{""}}	{{- template "object" . }}
	{{- end }}
{{- end }}

{{- /* This module's root client: the fields it contributes to Query, as an
ordinary class. A module whose contribution carries no root fields (nothing to
call) still gets the class so `dag` below always exists. */ -}}
{{- $root := RootClientType .Types }}
{{- if and $root $root.Fields }}
{{""}}
{{- template "object" $root }}
{{- else }}
{{""}}
export class Client extends BaseClient {}
{{- end }}

{{ if .Bound }}
{{- /* Serve this module into the session before the first query that reaches it,
so a caller — this module's source, another module, or the entrypoint loading a
value of this module's type — resolves it without a central serve. Memoized per
session by the module's own source. */}}
async function __serveModule(): Promise<void> {
{{- if IsGitModule .Bound.Kind }}
  await __dag.moduleSource({{ JSString .Bound.Ref }}, { refPin: {{ JSString .Bound.Pin }} }).asModule().serve()
{{- else }}
  {{- /* A local module resolves against the workspace by its root-relative path;
  currentWorkspace is reached by raw query because it is kept out of a module's
  generated bindings. */}}
  await (__dag as any).getGQLClient().request(
    `{ currentWorkspace { moduleSource(path: {{ JSString (WorkspacePath .Bound.Path) }}) { asModule { serve } } } }`,
  )
{{- end }}
}

// A context that serves this module before its first query. `dag` uses it, and
// the entrypoint loader uses it to wrap a received value of this module's type,
// so both paths serve the module lazily on use.
export function __servedContext(): Context {
  return new Context().withServe({ key: {{ JSString .DepName }}, run: __serveModule })
}
{{- else }}
{{- /* No bound source (a manifest dependency the engine serves, or the library's
own bindings): the context serves nothing. Exported all the same so the loader
can treat every module client uniformly. */}}
export function __servedContext(): Context {
  return new Context()
}
{{- end }}

export const dag = new Client(__servedContext())

{{- /* Top-level functions mirroring the root fields, bound to this module's
dag. A root field named like a TS keyword stays reachable through dag only — a
keyword cannot be a top-level function name. */ -}}
{{- if $root }}
{{- range $field := $root.Fields }}
{{- if not ($field.Name | IsKeyword) }}
{{- $required := GetRequiredArgs $field.Args }}
{{- $optionals := GetOptionalArgs $field.Args }}
export function {{ $field.Name | FormatMemberName }}({{ if $required }}{{ template "args" $field }}{{ end }}{{ if $optionals }}{{ if $required }}, {{ end }}opts?: Client{{ $field.Name | PascalCase }}Opts{{ end }}): {{ if Solve $field }}Promise<{{ if $field.TypeRef.IsVoid }}void{{ else }}{{ $field | FormatFieldReturnType }}{{ if IsNullableObject $field.TypeRef }} | null{{ end }}{{ end }}>{{ else }}{{ $field.TypeRef | FormatOutputType }}{{ end }} {
  return dag.{{ $field.Name | FormatMemberName }}({{ range $i, $a := $required }}{{ if $i }}, {{ end }}{{ $a.Name | FormatName }}{{ end }}{{ if $optionals }}{{ if $required }}, {{ end }}opts{{ end }})
}
{{ "" }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
