{{- /* Backward-compatibility shim for pre-1.0 `dag.<module>()` source.

Before unified clients, codegen merged every module's root fields into the one
core Client, so a module wrote `dag.myDep().hello()`. Each module is its own
client now, with its own Client and its own `dag`, and the core Client carries
no `<module>()` — so migrated source compiles under a type-stripping loader and
fails at dispatch with "dag.myDep is not a function".

This file puts those fields back, deprecated: one delegating method per root
field of every module client in the scope, installed on the core
Client.prototype, plus the declaration merge that lets an editor and tsc see
them.

It is a file of its own rather than part of the core bindings because core must
not reference a module client — the direction the design forbids (an ESM cycle,
and sdk/ has to stay a publishable core-only library). Only the loader imports
it, which keeps the direction entrypoint -> loader -> compat -> clients.

Each method delegates through the module client's own `dag`, not through a raw
query, so the client's serve-on-use hook still runs and the module is served
before the first query reaches it. */ -}}
{{ define "compat" -}}
/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
{{- $clients := CompatClients }}
{{- if not $clients }}
{{ "" }}
// No module client contributes a root field, so there is nothing to put back
// on the core client.
export {}
{{- else }}
{{- /* The core Client is imported for its prototype alone. Through the package
rather than the core file, so the class patched here is the one the module's own
source resolves. */}}
import { Client } from "@dagger.io/dagger"
{{- range $client := $clients }}
import { dag as {{ $client.DagAlias }} } from "{{ $client.From }}"
{{- end }}
{{- range $imp := CompatImports }}
import type {
{{- range $i, $n := $imp.Types }}{{ if $i }},{{ end }}
  {{ $n }}
{{- end }}
} from "{{ $imp.From }}"
{{- end }}
{{ "" }}
declare module "@dagger.io/dagger" {
  interface Client {
{{- range $client := $clients }}
{{- range $field := $client.Fields }}
{{- $required := GetRequiredArgs $field.Args }}
{{- $optionals := GetOptionalArgs $field.Args }}
    /**
     * @deprecated Reach {{ $client.Module }} through its own client instead: `import { {{ $field.Name | FormatMemberName }} } from "{{ $client.Package }}"`.
     */
    {{ $field.Name | FormatMemberName }}({{ if $required }}{{ template "args" $field }}{{ end }}{{ if $optionals }}{{ if $required }}, {{ end }}opts?: {{ CompatOptsName $field }}{{ end }}): {{ if Solve $field }}Promise<{{ if $field.TypeRef.IsVoid }}void{{ else }}{{ $field | FormatFieldReturnType }}{{ if IsNullableObject $field.TypeRef }} | null{{ end }}{{ end }}>{{ else }}{{ $field.TypeRef | FormatOutputType }}{{ end }}
{{- end }}
{{- end }}
  }
}
{{ "" }}
{{- /* Non-enumerable, so a restored method stays out of Object.keys and of
anything that walks a client's own members: it is compatibility surface, not
part of the API. */}}
const __install = (name: string, impl: (...args: any[]) => any): void => {
  Object.defineProperty(Client.prototype, name, {
    configurable: true,
    enumerable: false,
    writable: true,
    value: impl,
  })
}
{{- range $client := $clients }}
{{- range $field := $client.Fields }}
{{ "" }}
__install({{ $field.Name | FormatMemberName | printf "%q" }}, (...args: any[]) =>
  ({{ $client.DagAlias }}.{{ $field.Name | FormatMemberName }} as any)(...args),
)
{{- end }}
{{- end }}
{{- end }}
{{ end }}
