{{- /* Object loader for the generated entrypoints.

The dispatcher receives dependency- and core-typed values as IDs and must wrap
each in its generated client class. With every module in its own file there is
no single namespace to look a class up in, and searching the files in order
would resolve a name two modules both export by accident of ordering — so the
map is explicit: codegen knows each type's owning file from the schema split
and bakes it here. Only the entrypoints import this file; client files never
import it, so the dependency direction stays entrypoint -> loader -> clients.
*/ -}}
{{ define "loader" -}}
/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
import { Context } from "@dagger.io/dagger"
{{- range $f := LoaderFiles }}
import * as {{ $f.Alias }} from "{{ $f.From }}"
{{- end }}

// Each entry pairs a type's client class with a context factory. A module type
// is wrapped in its owning client's served context, so loading a received value
// of that type serves the module before the load runs — the same lazy serve a
// direct `dag.<module>()` call gets. Core types need no serve.
type LoaderEntry = { cls: any; ctx: () => Context }

const __classes: Record<string, LoaderEntry> = {
{{- range $f := LoaderFiles }}
{{- range $e := $f.Entries }}
  {{ $e.TypeName | printf "%q" }}: { cls: {{ $f.Alias }}.{{ $e.ClassName }}, ctx: {{ if eq $f.Alias "__core" }}() => new Context(){{ else }}{{ $f.Alias }}.__servedContext{{ end }} },
{{- end }}
{{- end }}
}

// Load a core/module object from its ID via node(id:) and wrap it in the
// matching generated client class, whichever generated file that class lives
// in. Replaces the retired load<Type>FromID API (removed in #12041).
export function __loadObject(id: string, typeName: string): any {
  const entry = __classes[typeName]
  if (!entry) {
    throw new Error(`generated client class not found for type: ${typeName}`)
  }
  return new entry.cls(entry.ctx().selectNode(id, typeName))
}
{{- end }}
