{{- /* Object loader for the generated entrypoints.

The dispatcher receives dependency- and core-typed values as IDs and must wrap
each in its generated client class. With every module in its own file there is
no single namespace to look a class up in, and searching the files in order
would resolve a name two modules both export by accident of ordering — so the
map is explicit: codegen knows each type's owning file from the schema split
and bakes it here. Only the entrypoints import this file; client files never
import it, so the dependency direction stays entrypoint -> loader -> clients.
*/ -}}
{{ define "loader" -}}
/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
{{- if IsBundle }}
import { Context } from "./core.js"
{{- else if (not IsClientOnly) }}
import { Context } from "../common/context.js"
{{- else }}
import { Context } from "@dagger.io/dagger"
{{- end }}
{{- range $f := LoaderFiles }}
import * as {{ $f.Alias }} from "./{{ $f.File }}.js"
{{- end }}

const __classes: Record<string, any> = {
{{- range $f := LoaderFiles }}
{{- range $e := $f.Entries }}
  {{ $e.TypeName | printf "%q" }}: {{ $f.Alias }}.{{ $e.ClassName }},
{{- end }}
{{- end }}
}

// Load a core/module object from its ID via node(id:) and wrap it in the
// matching generated client class, whichever generated file that class lives
// in. Replaces the retired load<Type>FromID API (removed in #12041).
export function __loadObject(id: string, typeName: string): any {
  const cls = __classes[typeName]
  if (!cls) {
    throw new Error(`generated client class not found for type: ${typeName}`)
  }
  return new cls(new Context().selectNode(id, typeName))
}
{{- end }}
