{{- /* Header template.
A static file to define BaseClient class that will be
inherited by futures objects and common types.
 */ -}}
{{ define "header" -}}
/**
 * This file was auto-generated by `client-gen`.
 * Do not make direct changes to the file.
 */
 {{- if IsBundle }}
import { Context, BaseClient } from "./core.js"
{{- else }}
import { Context, BaseClient } from "../common/context.js"
{{- end }}

/**
 * Declare a number as float in the Dagger API.
 */
export type float = number

// BaseClient is re-exported so consumers that previously did
// `import { BaseClient } from "./client.gen.js"` keep working; the class
// itself lives in the common SDK runtime (see ../common/context.ts).
export { BaseClient }
{{- end }}
