{{- /*
Top-level template for the manifest-v2 dispatcher, __dagger.dispatch.ts.

It is the same file as __dagger.entrypoint.ts minus register(): under a module
entrypoint the typedefs come from the generated Dang program, evaluated in the
engine, so the container only ever exists to run a real call. What is left is the
dispatch half — the iface wrappers, the per-object rebuild/serialize helpers,
and invoke() — behind a stdin/stdout protocol.

Generated alongside __dagger.entrypoint.ts rather than replacing it: no engine
loads it yet, so nothing regresses while both are written.
*/ -}}
{{- define "dispatch_entrypoint" -}}
// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen entrypoint --dispatch).
{{ template "entrypoint_imports" . }}
{{- if .Interfaces }}

{{ template "entrypoint_iface_classes" . }}
{{- end }}

{{ template "entrypoint_state_helpers" . }}

{{ template "entrypoint_dispatch_v2" . }}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
{{- end -}}
