{{- /*
Top-level template for the manifest-v2 dispatcher, __dagger.dispatch.ts.

It is the same file as __dagger.entrypoint.ts minus register(): under a module
entrypoint the typedefs come from the generated Dang program, evaluated in the
engine, so the container only ever exists to run a real call. What is left is the
dispatch half — the iface wrappers, the per-object rebuild/serialize helpers,
and invoke() — behind a stdin/stdout protocol.

The protocol: one JSON request on stdin, one JSON reply on stdout (CallReply in
dispatch_v2), logs on stderr. The reply carries either the function's result or
the error it threw, and the process exits 0 in both cases: the entrypoint raises
a carried error as the function's own, with its message, where a nonzero exit
would surface as the exec's "exit code: 1". A nonzero exit is kept for the
dispatcher itself failing — an unreadable request, a session that never came
up — and stays a hard failure.
*/ -}}
{{- define "dispatch_entrypoint" -}}
// AUTO-GENERATED — DO NOT EDIT.
// Generated by Dagger TypeScript SDK introspector (cmd/codegen entrypoint --dispatch).
{{ template "entrypoint_imports" . }}
{{- if .Interfaces }}

{{ template "entrypoint_iface_classes" . }}
{{- end }}

{{ template "entrypoint_state_helpers" . }}

{{ template "entrypoint_dispatch_v2" . }}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
{{- end -}}
