name = "engine-e2e"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "engine-dev"
  source = "github.com/dagger/dagger/.dagger/modules/engine-dev@7e6fc93c86f0bf0eebae8c2c74a249c3b5cc451f"
