name = "engine-e2e"
engineVersion = "v1.0.0-0"

[runtime]
  source = "dang"

[[dependencies]]
  name = "engine-dev"
  source = "github.com/dagger/dagger/.dagger/modules/engine-dev@main"
  pin = "adf3da88f688a7bb27604980f180425140158811"
