{{- /*
Top-level template for the generated entrypoint/main.dang.

The engine loads this program directly and never calls the SDK module to load or
run the module. It implements ModuleEntrypoint: types() returns the module's
typedefs as literals, evaluated in-process with no container; call() builds the
container and dispatches one call to the generated TypeScript dispatcher.

The ModuleEntrypoint interface is not declared here — the dang driver writes
__module_entrypoint.dang into the directory it loads, so declaring it would
collide.
*/ -}}
{{- define "dang_entrypoint" -}}
# Code generated by Dagger. DO NOT EDIT.

type Entrypoint implements ModuleEntrypoint {
  """
  Every type this module defines.

  Evaluated in the engine, with no container: these are the same typedefs the
  runtime used to register by chaining API calls from inside a running node
  process. A name-only reference such as `typeDef.withObject("Foo")` binds to the
  full definition in this list, by kind and original name.
  """
  pub types(workspace: Workspace!): [TypeDef!]! {
{{- $entries := dangTypeEntries }}
{{- if $entries }}
    [
{{- range $entry := $entries }}
      {{ $entry }},
{{- end }}
    ]
{{- else }}
    []
{{- end }}
  }

  """
  Run one constructor or function and return its JSON result.

  The request goes in on stdin and the reply comes back on stdout as one JSON
  object, a DispatchReply: `result` carries the function's result, `error` what
  it threw. The dispatcher exits 0 either way and the error travels as data,
  because this is the only way its message reaches the caller: raised here it
  becomes the function's own error, as returnError made it under the builtin
  runtime, where a nonzero exit surfaces as the exec's "exit code: 1" with the
  message buried in the exec log. A nonzero exit is therefore the dispatcher
  itself failing, not the function, and stays an exec error.

  There is no session channel and no FunctionCall round-trip, so the
  dispatcher's logs have to go to stderr to keep stdout clean.
  """
  pub call(
    workspace: Workspace!,
    receiverType: String!,
    receiverValue: JSON,
    fnName: String!,
    fnArgs: JSON!,
  ): JSON! {
    let checked = requireGenerated(workspace)
    let request = JSON.encode({{"{{"}}
      receiverType: receiverType,
      receiverValue: receiverValue,
      fnName: fnName,
      fnArgs: fnArgs,
    {{"}}"}})
    let reply = JSON.decode(
      runtime(workspace)
        .withExec({{ dangDispatchExec }}, stdin: request)
        .stdout,
    ) :: DispatchReply!
    let failure = reply.error
    if (failure != null) {
      raise failure.message
    }
    let result = reply.result
    if (result == null) {
      raise "the dispatcher replied with neither a result nor an error"
    }
    result
  }

  """
  The container a call runs in, minus the exec that runs it.

  Every value here was decided when this file was generated: the image, the
  loader, the package manager, the mount layout. Nothing is re-derived at call
  time, so changing the runtime or the module's layout means re-running
  `dagger generate`. Keeping the exec out of this helper is what lets the whole
  build be shared across calls, and across modules that share a prefix.
  """
  let runtime(workspace: Workspace!): Container! {
    {{ dangRuntimeChain }}
  }

  """
  The image every container here starts from, with whatever the JS runtime needs
  before anything module-specific.

  Shared by runtime() and dependencies() so the pull, the prefix and the package
  cache are one layer for both rather than two chains that happen to agree.
  """
  let base: Container! {
    {{ dangBaseChain }}
  }

  """
  The module's dependencies, installed, as the node_modules a call mounts.

  Built from the module's manifest and lockfile alone — never from its source —
  so editing a function reinstalls nothing. That is also why the install cannot
  live in runtime(): every exec after the workspace is mounted is keyed on the
  whole workspace, and anything installed before it under the mount point would
  be hidden by it.
  """
  let dependencies(workspace: Workspace!): Directory! {
    {{ dangDependenciesChain }}
  }

  """
  Fail with something actionable when a generated file is missing.

  The engine's builtin TypeScript runtime checks this before it builds its
  container, but under an entrypoint nothing runs that runtime — this program
  builds the container itself, so the check has to live here too. Without it a
  gitignored sdk/ surfaces as a module resolution error from inside a container,
  several layers away from the cause.

  Only call() needs it. types() is literals, so a module whose generated tree is
  missing still lists its functions and then fails at the first real call —
  which is the point: the failure names the file and the fix.
  """
  let requireGenerated(workspace: Workspace!): Void {
    {{ dangRequireGeneratedBody }}
  }
}

"""
What the dispatcher writes to stdout: `result` when the call returned, `error`
when it threw, never both.

`result` is the function's return value as a JSON string — a string rather than
an embedded value for the same reason the request's receiverValue and fnArgs
are: a JSON scalar decodes from a string, and the engine gets the value back
verbatim.
"""
type DispatchReply {
  result: JSON
  error: DispatchError
}

"""
A thrown error as the dispatcher reports it: the message, and nothing else.

The stack is on the dispatcher's stderr, which is the exec log. The values a
typed error carried as extensions through returnError under the builtin runtime
do not cross this boundary: call() can raise nothing richer than a message.
"""
type DispatchError {
  message: String!
}
{{- end -}}
