{{- /*
Top-level template for the generated entrypoint/main.dang.

The engine loads this program directly and never calls the SDK module to load or
run the module. It implements ModuleEntrypoint: types() returns the module's
typedefs as literals, evaluated in-process with no container; call() builds the
container and dispatches one call to the generated TypeScript dispatcher.

The ModuleEntrypoint interface is not declared here — the dang driver writes
__module_entrypoint.dang into the directory it loads, so declaring it would
collide.
*/ -}}
{{- define "dang_entrypoint" -}}
# Code generated by Dagger. DO NOT EDIT.

type Entrypoint implements ModuleEntrypoint {
  """
  Every type this module defines.

  Evaluated in the engine, with no container: these are the same typedefs the
  runtime used to register by chaining API calls from inside a running node
  process. A name-only reference such as `typeDef.withObject("Foo")` binds to the
  full definition in this list, by kind and original name.
  """
  pub types(workspace: Workspace!): [TypeDef!]! {
{{- $entries := dangTypeEntries }}
{{- if $entries }}
    [
{{- range $entry := $entries }}
      {{ $entry }},
{{- end }}
    ]
{{- else }}
    []
{{- end }}
  }

  """
  Run one constructor or function and return its JSON result.

  The request goes in on stdin and the result comes back on stdout; a nonzero
  exit is a function error. There is no session channel and no FunctionCall
  round-trip, so the dispatcher's logs have to go to stderr to keep stdout clean.
  """
  pub call(
    workspace: Workspace!,
    receiverType: String!,
    receiverValue: JSON,
    fnName: String!,
    fnArgs: JSON!,
  ): JSON! {
    let checked = requireGenerated(workspace)
    let request = JSON.encode({{"{{"}}
      receiverType: receiverType,
      receiverValue: receiverValue,
      fnName: fnName,
      fnArgs: fnArgs,
    {{"}}"}})
    (runtime(workspace)
      .withExec(
        {{ dangDispatchExec }},
        stdin: request,
        experimentalPrivilegedNesting: true,
      )
      .stdout :: JSON!)
  }

  """
  The container a call runs in, minus the exec that runs it.

  Every value here was decided when this file was generated: the image, the
  loader, the mount layout. Nothing is re-derived at call time, so changing the
  runtime or the module's layout means re-running `dagger generate`. Keeping the
  exec out of this helper is what lets the whole build be shared across calls,
  and across modules that share a prefix.
  """
  let runtime(workspace: Workspace!): Container! {
    {{ dangRuntimeChain }}
  }

  """
  Fail with something actionable when a generated file is missing.

  The engine's builtin TypeScript runtime checks this before it builds its
  container, but under an entrypoint nothing runs that runtime — this program
  builds the container itself, so the check has to live here too. Without it a
  gitignored sdk/ surfaces as a module resolution error from inside a container,
  several layers away from the cause.

  Only call() needs it. types() is literals, so a module whose generated tree is
  missing still lists its functions and then fails at the first real call —
  which is the point: the failure names the file and the fix.
  """
  let requireGenerated(workspace: Workspace!): Void {
    {{ dangRequireGeneratedBody }}
  }
}
{{- end -}}
